apiVersion: v1
kind: PersistentVolume
metadata:
  name: donkeycar-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: donkeycar-hostpath
  hostPath:
    path: /workspace
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: donkeycar-results-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: donkeycar-hostpath
  hostPath:
    path: /workspace/results/kubeflow_donkeycar_outputs
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: donkeycar-data-pvc
  namespace: kubeflow
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: donkeycar-hostpath
  resources:
    requests:
      storage: 20Gi
  volumeName: donkeycar-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: donkeycar-results-pvc
  namespace: kubeflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: donkeycar-hostpath
  resources:
    requests:
      storage: 10Gi
  volumeName: donkeycar-results-pv
