kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mytorch-donkeycar
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: "D:\\zs\\testmytorch - 副本"
        containerPath: /workspace
